 export const GET_CONTACTS_START = "GET_CONTACTS_START";
 export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
 export const GET_CONTACTS_FAILED = "GET_CONTACTS_FAILED";

 export const DELETE_CONTACT_START = "DELETE_CONTACT_START";
 export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
 export const DELETE_CONTACT_FAILED = "DELETE_CONTACT_FAILED";

 export const ADD_CONTACT_START = "ADD_CONTACT_START";
 export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
 export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED";

 export const EDIT_CONTACT_START = "EDIT_CONTACT_START";
 export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
 export const EDIT_CONTACT_FAILED = "EDIT_CONTACT_FAILED";